aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    working_directory: ~/docusaurus
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy WxP WebSite
          command: |
            ls
            # config user
            git config --global user.email "singletouch@163.com"
            git config --global user.name "Website Deployment Script"
            # install
            cd website && npm install
            # publish
            CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  tests-and-deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master