aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn
  - &filter-only-master
    branches:
      only:
        - master

defaults: &defaults
  working_directory: ~/docusaurus
  docker:
    - image: circleci/node:10

version: 2
jobs:
  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - run: *root-yarn
      - run:
          name: Configure GitHub Bot
          # Do not do this if we don't have the right org (facebook), or if this is just a pull request
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME == "wxp-ui" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              git config --global user.email "singletouch@163.com"
              git config --global user.name "Website Deployment Script"
              echo "machine github.com login singletouch password $DOCUSAURUS_PUBLISH_TOKEN" > ~/.netrc
            fi

      - run: ls
      - run: echo $CIRCLE_PROJECT_USERNAME
      - run: echo $CI_PULL_REQUEST
      - run: echo $CIRCLE_PR_USERNAME
      - run:
          name: Deploy v1 Website
          # Skip the deploy if we don't have the right org (facebook), or if this is just a pull request
          command: |
            echo "Deploying website..."
            ls
            cat package.json
            # publish
            GIT_USER=singletouch USE_SSH=true yarn run publish-gh-pages
# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  tests-and-deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master