aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn
  - &filter-only-master
    branches:
      only:
        - master

defaults: &defaults
  working_directory: ~/docusaurus
  docker:
    - image: circleci/node:10

version: 2
jobs:
  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - run: *root-yarn
      - run:
          name: Configure GitHub Bot
          # Do not do this if we don't have the right org (facebook), or if this is just a pull request
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME == "wxp-ui" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              git config --global user.email "singletouch@163.com"
              git config --global user.name "Website Deployment Script"
              echo "machine github.com login singletouch password $DOCUSAURUS_PUBLISH_TOKEN" > ~/.netrc
            fi
      - run:
          name: Deploy v1 Website
          # Skip the deploy if we don't have the right org (facebook), or if this is just a pull request
          command: |
            if ! git diff-tree --no-commit-id --name-only -r HEAD | grep -E "(^docs\/.*)|(docusaurus-1\.x\/.*)|(website-1\.x\/.*)"; then
              echo "Skipping deploy. No relevant v1 website files have changed"
            elif [[ $CIRCLE_PROJECT_USERNAME == "wxp-ui" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              echo "Deploying website..."
              # install Docusaurus and generate file of English strings
              cd website-1.x && yarn run write-translations
              # install Crowdin
              sudo apt-get update
              sudo apt-get install default-jre rsync
              wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
              sudo dpkg -i crowdin.deb
              sleep 5
              # upload translation strings and download translations
              yarn run crowdin-upload
              # download only enabled languages
              for lang in fr ko ru ro pt-BR zh-CN
              do
                  yarn crowdin-download -l $lang
              done
              # publish
              GIT_USER=singletouch USE_SSH=true yarn run publish-gh-pages
            else
              echo "Skipping deploy."
            fi
# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  tests-and-deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master