aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:34:e6:3b:8e:7f:c7:34:cc:a3:b2:e7:3a:6b:15:dc"
      - checkout
      - run:
          name: Deploy WxP WebSite
          command: |
            # config user
            git config --global user.email "singletouch@163.com"
            git config --global user.name "Website Deployment Script"
            # install
            cd website && npm install
            # publish
            CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-website:
          filters: *filter-ignore-gh-pages