machine:
  node:
    version: 6.11.2
  npm:
    version: 3.10.10
version: 2
jobs:
  build:
    machine: true
    branches:
      ignore: gh-pages
    steps:
      - run: echo "Skipping tests on gh-pages branch"
deployment:
  website:
    branch: master
    command: |
      git config --global user.email "singletouch@163.com"
      git config --global user.name "singletouch"
      echo "machine github.com login wxp-ui password $GITHUB_TOKEN" > ~/.netrc
      cd website && yarn install && CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages

