machine:
  node:
    version: 6.11.2
  npm:
    version: 3.10.10
version: 2
jobs:
  build:
    machine: true
    branches:
      ignore: gh-pages
    steps:
      -run: echo "Skipping tests on gh-pages branch"
deployment:
  website:
    branch: master
    commands:
      - git config --global user.email "singletouch@163.com"
      - git config --global user.name "singletouch"
      - cd website && npm install && CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages