version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    machine: true
    steps:
      - run: echo "Skipping tests on gh-pages branch"
      - run: git config --global user.email "singletouch@163.com"
      - run: git config --global user.name "singletouch"
      - run: echo "machine github.com login singletouch password $GITHUB_TOKEN" > ~/.netrc
      - run: checkout
      - run: cd website && yarn install && CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages