aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:34:e6:3b:8e:7f:c7:34:cc:a3:b2:e7:3a:6b:15:dc"
      - checkout
      - run:
          name: Deploy WxP WebSite
          command: |
            echo git diff-tree --no-commit-id --name-only -r HEAD
            echo git diff-tree --no-commit-id --name-only -r HEAD | grep -E "(^docs\/.*)|(docusaurus\.x\/.*)|(website\.x\/.*)"
            if ! git diff-tree --no-commit-id --name-only -r HEAD | grep -E "(^docs\/.*)|(docusaurus\.x\/.*)|(website\.x\/.*)"; then
              echo "Skipping deploy. No relevant v1 website files have changed"
            elif [[ $CIRCLE_PROJECT_USERNAME == "wxp-ui" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              # config user
              git config --global user.email "singletouch@163.com"
              git config --global user.name "Website Deployment Script"
              # install
              cd website && npm install
              # publish
              CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages
            else
              echo "Skipping deploy."
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-website:
          filters: *filter-ignore-gh-pages